export const EVENT_IM_ENTER = 'IM_ENTER';
export const EVENT_IM_LEAVE = 'IM_LEAVE';
export const EVENT_IM_IDEA_ADD_FROM_CUSTOM = 'IM_IDEA_ADD_FROM_CUSTOM';
export const EVENT_IM_IDEA_EDIT = 'IM_IDEA_EDIT';
export const EVENT_IM_IDEA_DELETE  = 'IM_IDEA_DELETE';
export const EVENT_IM_IDEA_MOVE = 'IM_IDEA_MOVE';
export const EVENT_IM_LINE_ADD_FROM_CUSTOM = 'IM_LINE_ADD_FROM_CUSTOM';
export const EVNET_IM_LINE_DELETE = 'EVNET_IM_LINE_DELETE';

// deprecated
export const EVENT_IM_IDEA_ADD_FROM_CONTEXT = 'IM_IDEA_ADD_FROM_CONTEXT';
