export const EVENT_SM_SAVE = 'SEARCHMAPPER_SAVE';
export const EVENT_SM_DELETE = 'SEARCHMAPPER_DELETE';
export const EVENT_SM_THEME_CREATE = 'SEARCHMAPPER_CREATE_THEME';
export const EVENT_SM_THEME_ADD = 'SEARCHMAPPER_ADD_TO_THEME';
export const EVENT_SM_CHANGE_THEME = 'SEARCHMAPPER_CHANGE_THEME';
export const EVENT_SM_DELETE_THEME = 'SEARCHMAPPER_DELETE_THEME';