export const EVENT_NEW_SEARCH = 'NEW_SEARCH';
export const EVENT_SEARCH_RESULT_CLICKED = 'SEARCH_RESULT_CLICKED';
export const EVENT_SEARCH_SERP_ENTER = 'SERP_ENTER';
export const EVENT_SEARCH_SERP_LEAVE = 'SERP_LEAVE';