export const SM_SET_BUFFERED_SEARCH = 'SM_SET_BUFFERED_SEARCH';
export const SM_UPDATE_SAVED_RESULTS = 'SM_UPDATE_SAVED_RESULTS';
export const SM_SR_LOAD = 'SM_SR_LOAD';
export const SM_SR_LOAD_SUCCESS = 'SM_SR_LOAD_SUCCESS';
export const SM_SR_LOAD_FAIL = 'SM_SR_LOAD_FAIL';
export const SM_SR_REORDER = 'SM_SR_REORDER';
export const SM_SR_REORDER_SUCCESS = 'SM_SR_REORDER_SUCCESS';
export const SM_SR_REORDER_FAIL = 'SM_SR_REORDER_FAIL';