// search engine
export const SM_SET_BUFFERED_SEARCH = 'SM_SET_BUFFERED_SEARCH';

// search mapper
export const SM_SR_LOAD = 'SM_SR_LOAD';
export const SM_SR_LOAD_SUCCESS = 'SM_SR_LOAD_SUCCESS';
export const SM_SR_LOAD_FAIL = 'SM_SR_LOAD_FAIL';
export const SM_SR_ADD = 'SM_SR_ADD';
export const SM_SR_ADD_SUCCESS = 'SM_SR_ADD_SUCCESS';
export const SM_SR_ADD_FAIL = 'SM_SR_ADD_FAIL';
export const SM_SR_DELETE = 'SM_SR_DELETE';
export const SM_SR_DELETE_SUCCESS = 'SM_SR_DELETE_SUCCESS';
export const SM_SR_DELETE_FAIL = 'SM_SR_DELETE_FAIL';
export const SM_SR_RENAME_THEME = 'SM_SR_RENAME_THEME';
export const SM_SR_RENAME_THEME_SUCCESS = 'SM_SR_RENAME_THEME_SUCCESS';
export const SM_SR_RENAME_THEME_FAIL = 'SM_SR_RENAME_THEME_FAIL';
export const SM_SR_EDIT_THEME_IDEA = 'SM_SR_EDIT_THEME_IDEA';
export const SM_SR_EDIT_THEME_IDEA_SUCCESS = 'SM_SR_EDIT_THEME_IDEA_SUCCESS';
export const SM_SR_EDIT_THEME_IDEA_FAIL = 'SM_SR_EDIT_THEME_IDEA_FAIL';
export const SM_SR_CREATE_THEME = 'SM_SR_CREATE_THEME';
export const SM_SR_CREATE_THEME_SUCCESS = 'SM_SR_CREATE_THEME_SUCCESS';
export const SM_SR_CREATE_THEME_FAIL = 'SM_SR_CREATE_THEME_FAIL';
export const SM_SR_CHANGE_THEME = 'SM_SR_CHANGE_THEME';
export const SM_SR_CHANGE_THEME_SUCCESS = 'SM_SR_CHANGE_THEME_SUCCESS';
export const SM_SR_CHANGE_THEME_FAIL = 'SM_SR_CHANGE_THEME_FAIL';
export const SM_SR_DELETE_THEME = 'SM_SR_DELETE_THEME';
export const SM_SR_DELETE_THEME_SUCCESS = 'SM_SR_DELETE_THEME_SUCCESS';
export const SM_SR_DELETE_THEME_FAIL = 'SM_SR_DELETE_THEME_FAIL';

// dialogs
export const SM_MSG_DIALOG_FORM_THEME_OPEN = 'SM_MSG_DIALOG_FORM_THEME_OPEN';
export const SM_MSG_DIALOG_DELETE_THEME_OPEN = 'SM_MSG_DIALOG_DELETE_THEME_OPEN';
export const SM_MSG_DIALOG_CLOSE = 'SM_MSG_DIALOG_CLOSE';
export const SM_TXT_DIALOG_ADD_IDEA_OPEN = 'SM_TXT_DIALOG_ADD_IDEA_OPEN';
export const SM_TXT_DIALOG_EDIT_IDEA_OPEN = 'SM_TXT_DIALOG_EDIT_IDEA_OPEN';
export const SM_TXT_DIALOG_CREATE_THEME_OPEN = 'SM_TXT_DIALOG_CREATE_THEME_OPEN';
export const SM_TXT_DIALOG_RENAME_THEME_OPEN = 'SM_TXT_DIALOG_RENAME_THEME_OPEN';
export const SM_TXT_DIALOG_CLOSE = 'SM_TXT_DIALOG_CLOSE';
export const SM_THEME_DIALOG_ADD_OPEN = 'SM_THEME_DIALOG_ADD_OPEN';
export const SM_THEME_DIALOG_MOVE_OPEN = 'SM_THEME_DIALOG_MOVE_OPEN';
export const SM_THEME_DIALOG_CLOSE = 'SM_THEME_DIALOG_CLOSE';